filename:	Data/camra-sim-varying.csv
input_type:	csv_netcdf_cfar

sensor_configuration:
  type:						radar
  observation_type:			razel
  observation_size:			3
  latitude:					51.1483578
  longitude:				-1.4384458
  altitude:					0.081
  pd:			0.8
  kappa:		1
  lambda:		1
  clutter:		1
  R:			[0.005041, 0.005, 0.005]

filter_parameters_single_target:
  type:				ukf
  state_dim:		6
  motion_model:		cv			
  dt:				0.07

filter_parameters_multiple_target:
  type:				gmjott
  gm_max_size:		100
  birth_type:		uniform
  birth_num:		1
  birth_intensity:	1
  th_merge:			0.8
  th_prune:			1e-8
  th_estimate:		0.5
  pb:				1e-5
  ps:				0.999
  q_initial:		0.01
  birth_cov:		[3600, 3600, 3600, 10, 10, 10]
  beta_epsilon:		0.01
  
temp:
  clutter_mult_temp:	1
  ukf_sigma_sampler_w:	0.5

other:
  polar_motion_x: 0
  polar_motion_y: 0
  length_of_day: 0